### ISSUE TITLE
Kuroko does not read files with Windows \r\n newlines

### ISSUE THREAD

**Issue by valoeghese** [kuroko-lang/kuroko#13]
I was trying out Kuroko 1.1.1 on Windows 10, and I noticed that in souce files I wrote with multiple lines I would get the error:
`kuroko: could not read file 'hello.krk': No error`

Upon changing my newlines to UNIX (\n), Kuroko could read the file perfectly.

Thus it is safe to assume that kuroko.exe was failing to parse files that use Windows (\r\n) newlines.

**Comment by klange** [comment]
Odd, that message would suggest an issue with the `fread` call... is Windows giving a different size when I seek to the end of the file vs. the number of bytes it returns from the read because it’s doing newline conversion underneath? I don’t do much testing directly under Windows beyond the test suite, but I’ll see if removing the exact size check is enough to resolve this.

**Comment by valoeghese** [comment]
I'll check this again at the next stable release
