### ISSUE TITLE
[Termux] TypeError: __init__() expects list, not 'list'

### ISSUE THREAD

**Issue by anzhi0708** [kuroko-lang/kuroko#32]
```bash
~/downloads/kuroko $ ./kuroko
Kuroko 1.3.1 (Oct 18 2022 at 19:47:41) with clang 15.0.2
Type `help` for guidance, `paste()` to toggle automatic indentation, `license` for copyright information.
>>> list()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() expects list, not 'list'
>>> [1,2,3]
 => [1, 2, 3]
>>> range(5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() expects range, not 'range'
>>> list(range(5))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() expects range, not 'range'
>>>
```

```bash
~/.../kuroko/test $ ../kuroko testThreading.krk
Starting 10 threads.
Traceback (most recent call last):
  File "testThreading.krk", line 33, in <module>
    let numbers    = list(range(totalCount))
TypeError: __init__() expects range, not 'range'
```

**Comment by klange** [comment]
Can you tell me a bit about your environment - architecture, OS, etc.? Were there any unexpected warnings when building?

**Comment by klange** [comment]
I do not support building for Android under the default configuration, primarily because I don't have any modern Android devices available for testing and also because Android is very different from a typical Linux environment. Android is known to have issues related to _thread-local storage_, in particular, which is a critical requirement for Kuroko's default Linux build setup. I suggest you try disabling thread support by passing `KRK_DISABLE_THREADS=1` in your invocation to `make` - be sure to `make clean` first.

Could you also tell me what version of Android you are running? Some support for TLS has been available since Android 29, but I believe it still does not support the `initial-exec` model I attempt to use.

**Comment by klange** [comment]
I believe that's API 30, so it should have at least basic support for thread-local storage...

You can either try to build without thread support, which is your best bet, or you can also try removing line 37 of `src/vm.c` (`__attribute__((tls_model("initial-exec")))`), and see if either of those help.

**Comment by klange** [comment]
I'm still curious if disabling threads in general resolved the issue? Otherwise, I might set up an Android VM and explore this further, as it is a very bizarre issue for equality checks on classes to fail, but for the mechanism of printing a type name in the error message to function.

**Comment by klange** [comment]
I was not able to set up an aarch64 Android emulator through Android Studio on an x86-64 host - I will try again later on an M1 Mac. I did try on an x86-64 Android VM using Termux's latest package for `clang`, and did not encounter this issue even with the existing TLS model. I suspect the issue is specific to aarch64 Android. For reference, I have not encountered this issue on aarch64 Linux (with glibc), nor on other aarch64 ELF platforms (namely, my own), or on macOS.

**Comment by klange** [comment]
<img width="525" alt="Screen Shot 2022-10-20 at 8 43 35" src="https://user-images.githubusercontent.com/223546/196824995-e8e1567d-10fb-4583-bbd5-baebf14b4f3f.png">

Looks like MTE is to blame here - you can see the 0xb4 in the top byte of the address in the last debug line here, which is the arbitrarily-chosen tag byte Android's libc allocator uses. This demonstrates a broken aspect of MTE - the untagged pointer points to the same thing, but doesn't evaluate as equal.

We can disable heap pointer tagging early with `mallopt(M_BIONIC_SET_HEAP_TAGGING_LEVEL, M_HEAP_TAGGING_LEVEL_NONE)` and now everything works:

<img width="525" alt="Screen Shot 2022-10-20 at 8 54 16" src="https://user-images.githubusercontent.com/223546/196825865-71d7947e-09b6-485e-b939-ee91c257e06f.png">

**Comment by klange** [comment]
Another option for us is to recognize that all Kuroko objects are going to be heap-allocated and to bake this into how heap object pointers are extracted from boxed values:

```diff
--- a/src/kuroko/value.h
+++ b/src/kuroko/value.h
@@ -209,1 +209,1 @@
- #define AS_OBJECT(value)    ((KrkObj*)(uintptr_t)((value) & KRK_VAL_MASK_LOW))
+ #define AS_OBJECT(value)    ((KrkObj*)(uintptr_t)((value) & KRK_VAL_MASK_LOW | 0xB400000000000000))
```

This seems to work, though it relies on knowing what the libc will tag heap pointers with - something we could figure out at runtime, but at significant cost compared to hardcoding it here.

**Comment by klange** [comment]
I have pushed the latter fix behind a build flag. Compile with `make KRK_HEAP_TAG_BYTE=0xB4`. I tried to get this behind a suitable set of `#ifdef`s but `__ANDROID_API__` is unhelpfully set to a lower number than what would indicate MTE is going to be enabled. I may extend the Makefile to detect this more dynamically, but for now a bit of manual massaging should work.
